### ISSUE TITLE
[BUG] Realtime sysex embedded in sysex results in incorrect UMP data

### ISSUE THREAD

**Issue by MusicMaker** [microsoft/MIDI#375] opened 2024-07-26 04:15 UTC
**Describe the bug**
Per MIDI specification, MIDI 1.0 realtime messages can be included inside a sysex. For example F0 F8 01 02 03 FA F7 is a valid message. System tealtime messages are ACTIVE SENSING, CLOCK, STOP, START, CONTINUE, TUNE and RESET. System ccmmon messages or other status with bit 7 set are not allowed inside sysex.

Such data changed into USB packets would look like SOX REALTIME SYSEX SYSEX REALTIME EOX and the receiver of USB packets should separate the realtime data out  

**To Reproduce**
1. Connect a MIDI USB device that uses a legacy MIDI descriptor.
2. Install Windows Midi 2.0 driver  for the device
3. Install Developer preview 6
4. midi.exe service stop and then start 
5. start  midi ep monitor , select the device
6. Create USB packets and inject some real time USB packets inside of it. Transmit the packets out to Windows PC
    USB packets example:
System (F0) System Exclusive, with 20 data bytes 
7E7FF004 0000F80F 7A7C7D04 0000F80F 0000FB0F 0000FC0F 74767804 0000FF0F 0000FE0F 0000F90F 6E707204 0000FD0F 00F76C06 

8. Observe sysex data is not correct

![Screenshot from 2024-07-26 13-56-32](https://github.com/user-attachments/assets/1116b8c0-6f94-49a7-bc97-77daedde5528)

**Expected behavior**
Realtime UMP messages separated from the sysex. For example ALSA shows this, where the realtime messages result in seperate legacy realtime and sysex data . The sysex data does not include the realtime messages:
![Screenshot from 2024-07-25 23-37-43](https://github.com/user-attachments/assets/b75b265a-d026-4743-9448-609c2e44df95)

Using the MIDI 1.0 legacy driver (Same message)

![Screenshot from 2024-07-26 14-01-20](https://github.com/user-attachments/assets/d835beb2-4c48-49c9-9ead-eb01a4b0d638)

**Screenshots**

**Installer Name or Version**
Windows DP6 with DP2 MIDI 2.0 driver

**Desktop (please complete the following information):**
 -Win11 Canary

**Device information, if this is with an external MIDI device:**
 - DIY MCU and firmware to send MIDI USB packets to Windows PC
 
**Application Information**
MIDI.exe from DP6

**Additional context**
using the legacy Windows .10 driver and tools such as MIDI OX , Pocket view and Mountain utilities  all show such data incorrectly. This could be bugs in those tools or windows legacy MIDI 1.0 driver

**Comment by AmeNote-Michael** [comment] 2024-07-29 23:04
@MusicMaker please note, you tested with old driver - new driver properly removes the 0xf0 and 0xf7 from UMP data for SYSEX, although this should not matter in SYSEX processing. Also, there is a fix to a bug where a SYSEX status of 2 is correctly used to continue SYSEX.

Your other point however that data is improper is not correct - the system realtime is properly processed in these messages.

From the data you presented, please consider the following - the USB MIDI 1.0 data is as follows:

0x7E7FF004 - which is SYSEX start with data "f07f7e"
0x0000F80F - which is single byte transfer with realtime "f8"
0x7A7C7D04 - which is SYSEX continue with data "7d7c7a"
0x0000F80F - which is single byte transfer with realtime "f8"
0x0000FB0F - which is single byte transfer with realtime "fb"
etc.

Looking at the output data from midi endpoint monitor, it is correct (especially considering updated driver that will drop the "f0" and "f7":

0x3013f07f 0x7e000000 - which is UMP MT=3, Status=1, number of bytes=3 indicating sysex start with 3 bytes of data which are "f07f7e". NOTE, new driver will drop the "f0" so it will show 2 bytes respectively.

0x10f80000 - which is UMP MT=1 with data "f8"

0x30137d7c 0x7a000000 - which is UMP MT=3, Status = 1 (corrected to 2 in new driver), number of bytes = 3 indicating sysex continue with 3 byes of data which are "0x7d7c7a".

0x10f80000 - another "f8"

0x10fb0000 - which is UMP MT=1 with data "fb"

etc.

Essentially, if you use latest driver you are getting the correct data presented in the console application. Note that it is not expected that the console application will re-arrange data and present "nicely" like being presented in ALSA example. This is something that applications will do. @Psychlist1972 please comment.

Therefore, I consider this not a bug and should be closed, especially if you evaluate using latest test signed driver or upcoming attestation signed driver.

**Comment by Psychlist1972** [comment] 2024-07-30 13:08
Correct. The console displays the MIDI packets as they are, without changes. There's no compacting or displaying in MIDI 1.0 data format.

**Comment by Psychlist1972** [comment] 2024-07-30 16:19
Next version of the console now formats incoming SysEx bytes when using `--verbose`

![image](https://github.com/user-attachments/assets/fb0e26ec-2b1a-492c-b364-1a016b07998f)

**Comment by MusicMaker** [comment] 2024-08-01 15:02
Thank you. will test the case against the new driver when received.

**Comment by Psychlist1972** [comment] 2024-08-15 12:06
New driver is out as of today.

**Comment by Psychlist1972** [comment] 2024-08-16 19:23
Closing as fixed. If you find it not to be when testing, will reopen.

**Closed by Psychlist1972** 2024-08-16 19:23 UTC
Labels: bug :lady_beetle:, area-usb-driver :computer:, driver-august-2024-fixed

**Comment by MusicMaker** [comment] 2024-09-30 07:45
Regressed with 10.0.1.5 driver and DP6 midi.exe , this is fixed.

**Comment by Psychlist1972** [comment] 2024-09-30 15:28
> Regressed with 10.0.1.5 driver and DP6 midi.exe , this is fixed.

Pretty sure, along with the other comments on other bugs, you used a different word than you meant to. "Regressed" would mean this bug needs to be reopened due to it not being fixed.

**Comment by MusicMaker** [comment] 2024-10-01 05:05
Corrected regressed to regression tested.
