### ISSUE TITLE
[BUG] Sending messages without monitoring causes Green Screen with the USB MIDI 2.0 driver

### ISSUE THREAD

**Issue by m-komo** [microsoft/MIDI#307] opened 2024-04-11 08:54 UTC
**Describe the bug**
Sending a lots of messages without monitoring causes Green Screen.
This issue only occurs if the device is running with the USB MIDI 2.0 driver (UsbMidi2.sys) 

**To Reproduce**
1. Update ProtoZOA with the attached firmware. 
2. Attach ProtoZOA to PC and update the driver to the USB MIDI 2.0 driver (UsbMidi2.sys).
3. Open console and make sure there is no monitoring command (midi endpoint monitor) running.
4. Run "midi endpoint send-message 0x40123456 0x00000000 -p 0 -c 125000 -i".
5. Choose "ZOA-216" as an endpoint.
6. Repeat step 4 to 5 several times.

Green Screen occurs.
I faced two types of Green Screen, "ATTEMPTED_SWITCH_FROM_DPC" and "KERNEL_SECURITY_CHECK_FAILURE".

**Expected behavior**
No Green Screen.

**Installer Name or Version**
 - Service: Windows.MIDI.Services.Developer.Preview.5.x64.1.0.24066.2126.exe
 - Driver: Updated_USBMIDI2_10.0.1.4.zip

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OS Build: 26100.1

**Device information, if this is with an external MIDI device:**
 - Device: ProtoZOA w/attached firmware.
[ZOA-216.uf2.zip](https://github.com/microsoft/MIDI/files/14943780/ZOA-216.uf2.zip)

**Comment by MusicMaker** [comment] 2024-04-14 02:18
https://www.windowslatest.com/2024/04/06/windows-11-24h2-build-26100-causes-undocumented-issues-blocks-some-apps/
FYI  26001 is reported to be buggy.. I can't even download it anymore ATM.

**Comment by MusicMaker** [comment] 2024-04-15 02:50
Finally installed 26100.1 (after using a network cable and several retires)
Ran this command with Preview 5 midi driver on 26100 (with DYI MIDI 2.0 ARM hardware) for many times without issues.
I have an RP2040 ut no protozoa. Will try that FW

**Comment by MusicMaker** [comment] 2024-04-15 03:40
Loaded that FW in an off the shelf RP2040 board and ran that command many times.  it sens the data, Cannot reproduce the GSOD.

**Comment by symdeb** [comment] 2024-04-15 03:44
Got two crashes now of Windows 11.  (auto reboots)... but not when running the command. need further check.

**Comment by MusicMaker** [comment] 2024-04-15 04:03
Now fully reprodceuable. indeed an GSOD

**Comment by Psychlist1972** [comment] 2024-04-15 04:45
Thank you for the repro and the crash dump, @MusicMaker. 

> https://www.windowslatest.com/2024/04/06/windows-11-24h2-build-26100-causes-undocumented-issues-blocks-some-apps/ FYI 26001 is reported to be buggy with several GSODs.. I can't even do Windows update to it anymore ATM. (stuck at an older version which by itself is also a known issue and suggests a clean install)

If you want to get off the Canary train, I was told Dev channel has the ACX / USB updates in it now, so USB MIDI 2 will work on it.

**Comment by MusicMaker** [comment] 2024-04-15 06:51
Indeed. noticed the Dev channel works too.

**Comment by AmeNote-Michael** [comment] 2024-05-02 23:38
Needs further investigation and analysis.

@garydan42 thinking about it, the act of midi endpoint send-message will put driver into "run" state which will process the USB IN buffer and into double buffer. As there is no monitor or application, nothing will be feeding from double buffer. In code, the reaction is to drop data but then request to handle existing data.

We should actually respond with discarding oldest data and then putting new data in buffer. What is the design pattern for this?

However, does not explain GSOD - just noting what we should be doing.

**Comment by AmeNote-Michael** [comment] 2024-06-24 21:31
@garydan42 This issue is due to the "Run" state being set when a send-message occurs but nothing is reading from driver. If the device has data provided and the driver is in run state, driver will populate the double buffer stream for UMP IN with UMP data. If there is nothing reading from the UMP Data from that stream, it will eventually fill.

I suspect we should just drop old data - but what is design pattern here? How do I ensure I am not conflicting on memory with other software that may be accessing stream? Is it same as when dealing with buffer for write?

**Comment by garydan42** [comment] 2024-07-03 16:53
The pin instance shouldn't be in the run state unless someone is retrieving buffers from the cross-process queue. The code that instantiates the cross-process buffer also creates the worker threads that does the reads and callbacks. The service should be retrieving these messages, and if there are no clients listening, dropping them.

That's not to say that the cross-process queue can't become full because messages are arriving faster than they can be processed or the callback blocks or hangs. The expectation is that the newest messages are dropped in that case, not that the oldest are dropped. Architecturally there's no way to drop the oldest messages because it's a producer/consumer fifo with the reader owning removing messages from the front of the fifo and the writer adding messages to the end. To drop the oldest messages the current read position would have to be advanced by the writer thread, but the reader may be actively reading at the current read position and modifying it would lead to data corruption.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by m-komo** [comment] 2024-07-18 05:47
I have confirmed that the issue has been solved.
- Service: Windows.MIDI.Services.In-Box.Service.-.Developer.Preview.6.1.0.24194.2233-x64.exe
- Driver: [interim preview build] 240713-USBMidi2-x86-TESTSIGNED.zip (DriverVer = 07/13/2024,23.1.50.504)
- OS: Windows 11 24H2 (OS Build 26100.1150)

**Comment by MusicMaker** [comment] 2024-07-18 13:59
That's not to say that the cross-process queue can't become full because messages are arriving faster than they can be processed or the callback blocks or hangs. The expectation is that the newest messages are dropped in that case, 

This makes most sense, but could that not lead to a stall or a new reader process retrieving  a lot of old messages ? another way could be to reset the queue when the queue overflows, but then nothing should be reading it, otherwise it could end up reading a non valid UMP message and it needs to handle to skip over corrupt data.

**Comment by AmeNote-Michael** [comment] 2024-07-18 23:50
@garydan42 I am thinking that the correct response here should be that on processing a continuous reader data input, if it looks like another message could fill cross-process queue to full, should stop continuous reader - this should cause USB stack to start to queue and use its own flow control. Then some event (maybe reads from cross-process queue check to see if continuous reader needs to be restarted) would start the continuous reader once enough space exists for servicing a max size USB message.

This of course would take a bit of rework to driver - and should be made a feature request.

**Comment by AmeNote-Michael** [comment] 2024-07-20 05:03
@garydan42 @Psychlist1972 I feel that this original issue can be closed and that a new one indicating dropping USB data in large transfers should be created. Green screens no longer occurring I believe but fix may have created a new issue.

**Comment by Psychlist1972** [comment] 2024-08-16 19:25
Closing as fixed in the August 2024 driver release. If you find it not to be when testing, will reopen.

**Closed by Psychlist1972** 2024-08-16 19:25 UTC
Labels: bug :lady_beetle:, area-usb-driver :computer:, area-service-or-api :desktop_computer:, critical ‼️, driver-august-2024-fixed
