### ISSUE TITLE
[BUG]MIDI Service gets stuck when receiving 0xFD(0x10FD0000).

### ISSUE THREAD

**Issue by Sho-KDM** [microsoft/MIDI#397] opened 2024-09-17 04:24 UTC
**Describe the bug**
If I send an undefined system common message as 0xFD, MIDI Service seems to get stuck.
If this happens, MidiSrv cannot be stop/restart, and we need to force reboot OS for recovering.

This issue only occurs if the USB MIDI 1.0 device is running with the USB MIDI 2.0 driver (USBMidi2.sys).

If the USB MIDI 1.0 device is running with the USB MIDI 1.0 driver (USBAUDIO.sys) or if the USB MIDI 2.0 device is running with the USB MIDI 2.0 driver (USBMidi2.sys), this issue never happens.

**To Reproduce**
1. Set the Roland UM-ONE mk2 to class-compliant mode and short INPUPT and OUTPUT to loop back messages.
2. Attach the UM-ONE to PC.
3. Open the Device Manager and load the USB MIDI 2.0 driver (USBMidi2.sys) manually against the attached UM-ONE.
4. Open midi.exe in two windows.
5. From one, monitor UM-ONE.
6. From the other, run following command: 
    'midi endpoint send-message 0x10FD0000'
7. On the monitor window, press escape to stop monitoring.

Monitoring cannot be terminated.
If I run another send-message command, it seems to be stuck.
For recovery this situation, it needs to force restart OS.

**Expected behavior**
MIDI Service and midi console continue to work.

**Installer Name or Version**
- Windows.MIDI.Services.In-Box.Service.-.Developer.Preview.6.1.0.24194.2233-x64.exe

**Desktop (please complete the following information):**
 - OS: Windows 11 24H2 build 26100.1586

**Device information, if this is with an external MIDI device:**
 - Roland UM-ONE mk2
 - Driver: driver-august-2024-fixed(USBMIDI2_10.0.1.5_x64.zip)

**Application Information**
- midi.exe console app.

**Additional context**
This issue is forked from #245. As I commented in #245, that issue is still existing if I send specific command(0xFD(0x10FD0000)). But assignee requested to create the new issue. Thus I created this.

**Comment by Psychlist1972** [comment] 2024-09-26 23:33
Mostly Duplicate of #361 

@AmeNote-Michael did you ever merge to main the 0xFD code you said wasn't in the current driver source?

**Comment by AmeNote-Michael** [comment] 2024-10-07 21:45
Resolved with pull request #407

**Closed by AmeNote-Michael** 2024-10-07 21:45 UTC
Labels: bug :lady_beetle:, area-usb-driver :computer:
