### ISSUE TITLE
[BUG] Windows MIDI 2.0 (preview 5) driver ignores bNumGrpTrmBlock value in USB descriptor

### ISSUE THREAD

**Issue by MusicMaker** [microsoft/MIDI#297] opened 2024-03-12 08:56 UTC
**Describe the bug**
- When  the MIDI 2.0 device configuration descriptor defines 1  for bNumGrpTrmBlock in the Class-specific MS Bulk IN/OUT Endpoint Descriptor  and there are actually 2 GTBs returned from the USB command Group Terminal Blocks Descriptors Request, the  driver still uses the number of GTB's form this USB call and reports all the groups defined in those GTBs. In other words, it does not match and read  the numbers of GTBs as defined by  bNumGrpTrmBlock  

**To Reproduce**
- Example: Define bNumGrpTrmBlock  as 1 and return two GTBS in the Group Terminal Blocks Descriptors Request
- Run midi.exe endpoint properties and check the number of GTBs/groups.  It shows the groups from both GTB's.

**Expected behavior**
- Only use and show the groups from the number of GTB's in bNumGrpTrmBlock (this is Linux behavior as well)

**Installer Name or Version**
- midi.exe tool and driver from preview 5

**Desktop (please complete the following information):**
 - OS:  Windows 11 Insider Canary & Dev

**Device information, if this is with an external MIDI device:**
- custom
-  Windows MIDI 2.0 class driver, preview 5
 
**Application Information**
- N/A

**Additional context**
- N/A

**Comment by AmeNote-Michael** [comment] 2024-03-15 20:58
@MusicMaker is this actually a bug, or is it an incorrect implementation of the USB Descriptor?

The bNumGrpTrmBlock is part of the USB configuration descriptor whereas the actual Group terminal Blocks are accessed after you have selected the USB interface and the number is parsed from the provided data. An initial read of header informs driver of how much data is available to read, then it is read and parsed for the number of Group Terminal Block Descriptors.

The driver provides the data that is available and if there is more Group Terminal Descriptors than there are defined bNumGrpTrmBlocks, then the question is, is descriptor information entered correctly to spec?

Your point though does raise an interesting possible issue with our creation of Group Terminal Blocks when we connect to a USB MIDI 1.0 device. Need to investigate this.

@AmeNote-MikeKent do you have any thoughts here?

**Comment by AmeNote-MikeKent** [comment] 2024-03-16 00:29
@MusicMaker wrote: _"When the MIDI 2.0 device configuration descriptor defines 1 for bNumGrpTrmBlock in the Class-specific MS Bulk IN/OUT Endpoint Descriptor and there are actually 2 GTBs returned from the USB command Group Terminal Blocks Descriptors Request..."_
and
_"Example: Define bNumGrpTrmBlock as 1 and return two GTBS in the Group Terminal Blocks Descriptors Request"_

This seems to be an error in device design. Why does the device declare 1 for bNumGrpTrmBlock, but then return 2 GTBs for the request from the driver? Is there some reason for this mismatch?

**Comment by Psychlist1972** [comment] 2024-03-16 02:44
Unless there's a good reason not to be, which someone can articulate here (per Mike's question), the information in the device needs to be internally consistent. Otherwise, the behavior is undefined.

I do appreciate the bug report, though.

**Comment by MusicMaker** [comment] 2024-03-17 01:43
It's perhaps not a common case, but a scenario possibly could be of of device that  select its (active) GTB by changing the configuration descriptor. (A device could have multiple ones). The USB spec does not define it should only return the GTB(s) per the configuration descriptor. FWIW Linux only uses the number of and of GTB's in the configuration descriptor. Do not have an Android 13 /Mac / IoS deviceon hand to compare.

**Comment by Psychlist1972** [comment] 2024-03-17 04:08
> It's perhaps not a common case, but a scenario possibly could be a device that select its (active) GTB by changing the configuration descriptor. (A device could have multiple ones). The USB spec does not define it should only return the GTB(s) per the configuration descriptor. FWIW Linux only uses the number of and of GTB's in the configuration descriptor. Do not have an Android 13 /Mac / IoS deviceon hand to compare.

Thanks. That scenario should hopefully never happen. Both macOS and Windows cache the GTB info. To change the number of GTBs, on macOS, you'll need to completely delete the device and recreate it or change the vid/pid/serial. There was a recent MIDI Association discussion about this in the OS API working group.

And, as a reminder, GTBs are not the recommended approach, especially if a device needs flexibility for changing groups, names, etc. That's part of why Function Blocks were created and GTBs effectively deprecated for new designs.

**Comment by Psychlist1972** [comment] 2024-03-17 05:44
I think part of where you're coming from is because of how GTBs were originally designed to work in the spec, and then how it turned out they could actually be used later. The USB spec, like the first CI spec, has some things in it that just didn't work well in practice. That's no shade on the folks who created it, as it needed to be done (and quickly) at the time. Unfortunately, it's extremely difficult to amend the USB spec through the USB-IF. The MIDI protocol specs are much easier.

So things like having 255 declared GTBs and then using the `baAssoGrpTermBlkID` to associate them to multiple endpoints on the same device, just didn't work out. Effectively, what happened is every device had to declare GTBs for just that one endpoint in the interface, and start numbering them at 1. 

There are a few recommendations for setting up generic GTBs that will work in a Function-block-preferred world. For example, declaring a single GTB with all groups and MIDI 2.0 support. Those are the types of things the papers/posts Andrew and folks have been putting together are supposed to help device makers understand.

In the end, function blocks are more flexible and are preferred over GTBs. They are what GTBs were meant to be, but also work across transports other than just USB. A device which intends to declare GTBs, needs to return exactly the number of GTBs it intends to expose, and only those, and so the number and the total size will have a direct and correct relationship. If more flexibility is needed, the device should use function blocks.

**Comment by symdeb** [comment] 2024-03-20 15:15
Just a  last comment.  still believe this is not correct not to fix. There can easily be, valid, use cases where a device could have a stack of GTBs with their own start and end groups and number of groups, where a user chooses the configuration if  a device and the device reboots . The device could do this by just changing two  bytes it's configuration descriptor for the start GTB(s) and the number GTBs' to use.  Not fixing this prohibits this approach. It is not a matter of the MIDI USB spec, it is not meeting how configuration descriptors by USB are supposed to work and the driver to use the values. To do it correctly, would be a minor change by just respecting the values in the configuration descriptor instead of basing on the GTBs and ignoring what the configuration descriptor specifies. Linux does it correctly IMHO. Understand that there are higher priority issues, but not-fix seems not correct IMHO.

**Comment by MusicMaker** [comment] 2024-03-20 15:17
Just a last comment. still believe this is not correct not to fix. There can easily be, valid, use cases where a device could have a stack of GTBs with their own start and end groups and number of groups, where a user chooses the configuration if a device and the device reboots . The device could do this by just changing two bytes it's configuration descriptor for the start GTB(s) and the number GTBs' to use. Not fixing this prohibits this approach. It is not a matter of the MIDI USB spec, it is not meeting how configuration descriptors by USB are supposed to work and the driver to use the values. To do it correctly, would be a minor change by just respecting the values in the configuration descriptor instead of basing on the GTBs and ignoring what the configuration descriptor specifies. Linux does it correctly IMHO. Understand that there are higher priority issues, but not-fix seems not correct IMHO.

**Comment by Psychlist1972** [comment] 2024-03-20 23:44
> Just a last comment. still believe this is not correct not to fix. There can easily be, valid, use cases where a device could have a stack of GTBs with their own start and end groups and number of groups, where a user chooses the configuration in the UI or otherwise of a device and then device reboots to use the selected GTBs. The device could do this by just changing two bytes it's configuration descriptor for the start GTB(s) and the number GTBs' to use. Not fixing this prohibits this approach. It is not a matter of the MIDI USB spec, it is not meeting how configuration descriptors by USB are supposed to work and the driver to use the values. To do it correctly, would be a minor change by just respecting the values in the configuration descriptor instead of basing on the GTBs and ignoring what the configuration descriptor specifies. Linux does it correctly IMHO. Understand that there are higher priority issues, but not-fix seems not correct IMHO.

@AmeNote-Michael  @AmeNote-MikeKent can you bring @MusicMaker 's scenario to AMEI please for comment and prioritization? The code for this would be 100% in the driver because the service doesn't have access to any of the other header values. From what I can tell from the driver code, the `baAssoGrpTrmBlkId` array is never queried or used, so this would require rewriting your GTB loading routine in `Device.cpp`

I would want an AMEI position on:
1. Are they using the `baAssoGrpTrmBlkId` array to associate the blocks?
2. Should the above scenario be supported in the driver they have contracted you to develop? IOW, are they ever using a subset of GTBs in that array? Do they want you to change the code to handle it this way?
3. Will any of their devices break (do any of them incorrectly report these values) if implemented this way per-spec?

@MusicMaker again, I'm not sure why this issue is important to you, but I very highly encourage you not to focus your time on GTBs. If the MIDI Association were able to amend the original USB spec themselves, GTBs would be deprecated. Function blocks are what you should use for the flexibility you're talking about, and all the operating systems have invested in supporting those appropriately. Function Blocks were created exactly because of the deficiencies in GTBs and the need to have consistent definitions across transports.

Also please refer to table 5-4 in the USB spec because it's not just two bytes that will need to be changed -- it's an array that has to have `bNumGrpTrmBlock` elements. It's possible you may be confusing it with `nGroupTrm` and `nNumGroupTrm` which are the group terminals, not group terminal blocks. That array is not currently used in the code, but would need to be to support the scenarios you mention.

**Comment by Psychlist1972** [comment] 2024-03-21 03:20
@Amenote-Michael

The main difference compared to how you do it now is the use of the array in the header as indirect ref to the group terminal block entries. Seems the correct process to get GTBs should be:

1. Read the bNumGrpTrmBlock value from the header (you do that now)
2. Loop through the remaining bytes from 0 to bNumGrpTrmBlock-1 to get the included group terminal block numbers (this is not done today, as far as I can tell)
3. Find each included group terminal block entry using those numbers (not just a for loop with 0 to num blocks-1), and append to the data
4. Get the strings like you do now
5. Return the data with the numbers as provided in the group terminal block data

I would then need to check the API and make any updates in case I'm assuming a zero or one start for indexes.

**Comment by AmeNote-MikeKent** [comment] 2024-03-21 17:13
@Psychlist1972 wrote: _@AmeNote-Michael @AmeNote-MikeKent can you bring @MusicMaker 's scenario to AMEI please for comment and prioritization?_ 

I will ask 2 guys in AMEI their opinion. I will also check with another guy in USB-IF. I assume it might take a few days for them to reply.
Mike.

**Comment by Psychlist1972** [comment] 2024-07-31 18:15
@amenote-michael, I believe you have this fixed now, correct? If so, I'll add the tag.

**Comment by Psychlist1972** [comment] 2024-08-16 19:25
Closing as fixed in the August 2024 driver release. If you find it not to be when testing, will reopen.

**Closed by Psychlist1972** 2024-08-16 19:25 UTC
Labels: bug :lady_beetle:, area-usb-driver :computer:, critical ‼️, driver-august-2024-fixed

**Comment by MusicMaker** [comment] 2024-09-30 06:54
Regressed. the driver correctly respects bNumGrpTrmBlock now. It is also resilient having the wrong total length of all GTB data in the GTB header.

**Comment by Psychlist1972** [comment] 2024-09-30 15:25
> Regressed. the driver correctly respects bNumGrpTrmBlock now. It is also resilient having the wrong total length of all GTB data in the GTB header.

I'm a bit confused by this statement.  "Regressed" means the problem is back.
