### ISSUE TITLE
[BUG] MidiSrv gets stuck by sending MT3. 

### ISSUE THREAD

**Issue by m-komo** [microsoft/MIDI#300] opened 2024-03-14 08:21 UTC
**Describe the bug**
If I send a zero length System Exclusive message (F0 F7) in MT3 format, MIDI Service gets stuck.
If this happens, MidiSrv cannot be stopped and restarting OS is required.

This issue only occurs if I send a message to the USB MIDI 1.0 device running with the USB MIDI 2.0 driver (USBMidi2.sys).
If I send a same message to the USB MIDI 1.0 device running with the USB MIDI 1.0 driver (USBAUDIO.sys) or the USB MIDI 2.0 device running with the USB MIDI 2.0 driver (USBMidi2.sys), this issue never happens.

**To Reproduce**
1. Set the Roland UM-ONE mk2 to class-compliant mode and attach it to the UM-ONE to PC.
2. Assign the USB MIDI 2.0 driver (USBMidi2.sys) to the attached UM-ONE.
3. Open midi.exe in two windows.
4. From one, monitor UM-ONE.
5. From the other, run following command:
'midi endpoint send-message 0x30000000 0x00000000'
6. On the monitor window, press escape to stop monitoring.
Monitoring cannot be terminated.
And finally, it is necessary to restart OS to recover.

**Expected behavior**
The message '0x30000000 0x00000000' is looped back and MIDI Service and midi console continue to work.

**Installer Name or Version**
Windows.MIDI.Services.Developer.Preview.5.x64.1.0.24066.2126.exe

**Desktop (please complete the following information):**
- OS: Windows 11 24H2
- OS Build from Settings > System > About: 26080.1

**Device information, if this is with an external MIDI device:**
- Roland UM-ONE mk2
- USB MIDI 2.0 class driver (USBMidi2.sys) version 10.0.1.4

**Application Information**
midi.exe console app.

**Comment by Psychlist1972** [comment] 2024-03-16 02:49
This is a tough one Michael, as it's garbage data. MIDI Services passes it along because it fits the UMP message type and size, and we don't validate beyond that. 

If translation to valid byte stream message fails, I would just abort translating that UMP and discard it.

**Comment by Psychlist1972** [comment] 2024-03-17 03:38
@AmeNote-Michael I suppose you could just convert this case to empty sysex F0/F7 with no data in between. That would presumably be better than just dropping the message.

**Comment by AmeNote-Michael** [comment] 2024-05-02 23:40
@Psychlist1972 this will be resolved with new SYSEX handling in driver using AM Lib.

**Comment by AmeNote-Michael** [comment] 2024-05-02 23:40
Next attestation signed driver.

**Comment by AmeNote-Michael** [comment] 2024-06-24 20:12
The driver did not previous handle empty SYSEX message. Driver now handles empty SYSEX message F0 F7 in both directions: UMP <-> USB MIDI 1.0. and this is resolved in upcoming pull request.

**Comment by sat-okada** [comment] 2024-07-17 09:19
I have confirmed that this issue is resolved with the latest version of the driver (23.1.50.504) and dp6.

**Closed** 2024-07-18 08:15 UTC
Labels: bug :lady_beetle:, area-usb-driver :computer:, critical ‼️
