### ISSUE TITLE
[BUG] midi.exe received(or showed) wrong UMP event

### ISSUE THREAD

**Issue by dmiura** [microsoft/MIDI#182] opened 2023-12-28 09:04 UTC
**Applies To**
midi.exe(or MIDI services?)

**Describe the bug**
midi.exe received(or showed) wrong UMP event. 
This is similar but different issue from #174.

**To Reproduce**
We are using ProtoZOA with following firmware.
https://github.com/midi-mma/Amenote_Protozoa/blob/main/Releases/V0.4/ProtoZOA_Main.uf2
[ZoA_UUT.uf2.zip](https://github.com/microsoft/MIDI/files/13734003/ZoA_UUT.uf2.zip)
(When "5" button on ProtoZOA, it will send UMP message(Note On) with 500usec interval, "3" means 300usec.)

When ProtoZOA sends continuously UMP MIDI 2.0 Note On messages with interval e.g. 500usec, then it seems that some scheduled messages appeared different UMP event, around 100,000 messages as following screen shot.
It shows "###### HR" and shows unexpected UMP events in after "###### HR", probably those are old events which USB MIDI 2.0 Driver received previously.
<img width="867" alt="issue" src="https://github.com/microsoft/MIDI/assets/8167750/757c9646-deaf-4f7d-a74d-9bd229488dcc">

**Comment by Psychlist1972** [comment] 2023-12-31 19:14
Thanks.

**Comment by dmiura** [comment] 2024-01-09 01:59
We've confirmed with Developer Preview 3(Worked Around https://github.com/microsoft/MIDI/issues/182 also related to message scheduling), same issue still occurred in our environment.

![Unknown](https://github.com/microsoft/MIDI/assets/8167750/9e26b166-44ce-4572-b6d7-188959570e32)

**Comment by Psychlist1972** [comment] 2024-01-14 02:28
@dmiura If you are seeing this on Developer Preview 3, it's unrelated to message scheduling. Scheduling is bypassed in DP3

I can't reproduce this with any of the commercial MIDI devices I have or the loopback endpoints. Can you reproduce this with anything other than the protozoa?

**Comment by Psychlist1972** [comment] 2024-01-14 02:31
@garydan42 is it possible that the circular buffer (either the one connected to USB or the one connected to the client) is wrapping around here and resulting in this? I know you've taken pains to ensure that doesn't happen, but I can't think of how else this might happen.

**Comment by m-komo** [comment] 2024-01-15 03:49
@Psychlist1972 @dmiura 

This issue could be reproduced on Roland side with DP3.

![image](https://github.com/microsoft/MIDI/assets/114042371/918048a9-61d2-49db-993d-e819cc64301e)

I also checked USB log and verified that the messages sent from the device were no problem.

As you can see in the attached screen captures, unexpected UMP messages appear to be just 512 messages ago. 
As far as I remember, the size of the buffer between MIDIService and API/Driver was 4KB, so it can store 512 MT4 messages.
I'm not sure but the symptoms may change if you change the buffer size.

**Comment by Psychlist1972** [comment] 2024-01-15 18:58
@garydan42 @AmeNote-Michael  I've never run into this with the loopbacks, however, so either it's not a client (app<->service) xproc buffer issue, or timing is a component. Is it possible this is related to the messages being put into the buffer from the driver and that queue?

**Comment by Psychlist1972** [comment] 2024-01-15 20:24
I'm running the same firmware on protozoa and haven't had the out of order messages yet, but I do see what I assume are dropped messages (the second word is not incrementing by 0x1 each time). It started off fine, but higher numbers seem to skip.

![image](https://github.com/microsoft/MIDI/assets/1421146/991f22d1-e366-4d06-b523-565776bdb475)

(Note, I was capturing to file at the same time, so the latency is higher. Just filed a bug on that)

[protozoa-2024-01-15.midi2.txt](https://github.com/microsoft/MIDI/files/13942776/protozoa-2024-01-15.midi2.txt)

As I recall, dropped messages are expected if the client can't keep up with the incoming stream, but these aren't coming fast enough for me to think that's the problem here.

**Comment by Psychlist1972** [comment] 2024-01-15 22:38
Interestingly, I changed the client buffer size in MidiSrv from 4096 bytes to 512 bytes and the messages are now all coming in at around 300us. The larger buffer was 2x slower. I recall Gary mentioning that possibility in the past. 

So far, I'm not seeing any skipped messages, and still no out-of-order timestamps.

![image](https://github.com/microsoft/MIDI/assets/1421146/c9b60ef8-1fbe-4524-ad7e-f30c8192a421)

I do get bursts of faster messages from time to time. I'm guessing that there's a pile-up and wait somewhere and then in the next timeslice they can all be sent?

![image](https://github.com/microsoft/MIDI/assets/1421146/c1dd8582-a45c-4a1d-b1b2-45b797ef4149)

But nothing out of order

![image](https://github.com/microsoft/MIDI/assets/1421146/b92b72ed-9265-4cee-8012-83b1a21888eb)

The downside of small buffers is that messages will be more easily lost if the client or device can't keep up, and there isn't code in there that will wait until the queue frees up.

**Comment by Psychlist1972** [comment] 2024-01-15 23:53
Finally had a message displayed out of order. Given that the text at the bottom says no messages were received out of order (that's checked in the background thread handling incoming messages), and this is strangely at the last message, this may be a display issue. I'll look into it more. Difficult to repro this, though.

![image](https://github.com/microsoft/MIDI/assets/1421146/9c4b896f-ca4d-415d-b593-f511d58467fe)

**Comment by Psychlist1972** [comment] 2024-01-15 23:55
I didn't notice in the earlier screen shots that the index was also out of order. The index is generated in midi.exe.

So, been a long way around saying this is a problem in my code :)

The dropped messages are something else, however. I haven't been able to repro that now, which is annoying.

**Comment by Psychlist1972** [comment] 2024-01-16 01:36
I've made some significant performance changes to the console monitor. However, I cannot repro this specific issue at will to know if it will address it or not. 

I *can* say that if I press "1" on the ProtoZoa, I get messages that are all around 100 microseconds from message to message (there's definite jitter there, but it's in the +/- tens of microseconds) and I haven't had any dropped messages or messages received out of order.

![image](https://github.com/microsoft/MIDI/assets/1421146/e8c45c84-9a2a-476f-9f3c-56b3e9f488d4)

If this fixes the issue, the problems were all in the display, not in the data path between the service and the client. However, again, I can't repro the original problem at will, so I will await your feedback once you try this change.

Can you try this release preview, please?

https://github.com/microsoft/MIDI/releases/tag/dev-preview-4-daily1

**Comment by m-komo** [comment] 2024-01-16 02:18
@Psychlist1972 
I have tried to install DP4 after uninstalling DP3, but I couldn't.
Setup failed with the error below:
![image](https://github.com/microsoft/MIDI/assets/114042371/16e0c6aa-43fe-4728-b65b-90bf9c173ecb)

Any advice?

**Comment by Psychlist1972** [comment] 2024-01-16 02:51
> @Psychlist1972 I have tried to install DP4 after uninstalling DP3, but I couldn't. Setup failed with the error below: ![image](https://private-user-images.githubusercontent.com/114042371/296913158-16e0c6aa-43fe-4728-b65b-90bf9c173ecb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzMzMDEsIm5iZiI6MTcwNTM3MzAwMSwicGF0aCI6Ii8xMTQwNDIzNzEvMjk2OTEzMTU4LTE2ZTBjNmFhLTQzZmUtNDcyOC1iNjViLTkwYmY5YzE3M2VjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQwMjQzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzNiNTIyNmYwMGFjZDBlNjBhZThkOTU0ZmM3NTg1MjNmM2ZhODY5Njg1NDJmMWRhNTdmODZjZDcyN2U5ZDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QDnxtaBZh1_Ns7oX9mj2neOQBl3oPOk1ZofUiSVJ7Uk)
> 
> Any advice?

It's presumably because a component didn't register during install. I've only see this when something stuck around from before. May need to do a manual cleanup. Sorry about that.

1. Ensure you don't have the console app actively monitoring an endpoing. If you do, exit it.

2. Uninstall the previous release from Apps > Installed Apps in Settings.

![image](https://github.com/microsoft/MIDI/assets/1421146/4887395d-5256-408c-bf9a-9baf9eb1e861)

3. After that, check the Windows Services Console (search->Services) and see if "Microsoft MIDI Service" is still listed. If it is, right-click it and choose "Stop" 

![image](https://github.com/microsoft/MIDI/assets/1421146/16935555-8e76-4e88-a2d1-87852cd6344e)
![image](https://github.com/microsoft/MIDI/assets/1421146/7aaf00b6-dd02-47a0-a82e-7188ae53c3e3)

4. Then go into %ProgramFiles%\Windows MIDI Services and if it exists, delete all three subdirectories. (Will require administrator permission)

![image](https://github.com/microsoft/MIDI/assets/1421146/f855643d-ccee-4be8-956e-479295732b28)

Those steps should clear up anything that was lingering around.

5. Re-run the latest installer.

**Comment by m-komo** [comment] 2024-01-16 03:34
@Psychlist1972 
Thank you for your suggestion.
In my case, there is no installed MIDI Service, no running service and no installed files under %ProgramFiles%.
However, the installer still fails.
But it's okay, I will re-install windows.
It may take an hour, but for me it's not a pain. ;-)

**Comment by Psychlist1972** [comment] 2024-01-16 04:04
> @Psychlist1972 Thank you for your suggestion. In my case, there is no installed MIDI Service, no running service and no installed files under %ProgramFiles%. However, the installer still fails. But it's okay, I will re-install windows. It may take an hour, but for me it's not a pain. ;-)

Oh! Sorry. I do hope it works after you reinstall. I'll be up for a couple more hours if you need anything.

**Comment by Psychlist1972** [comment] 2024-01-16 04:36
> @Psychlist1972 Thank you for your suggestion. In my case, there is no installed MIDI Service, no running service and no installed files under %ProgramFiles%. However, the installer still fails. But it's okay, I will re-install windows. It may take an hour, but for me it's not a pain. ;-)

Andrew also mentioned having issues with the install from this one. I'm testing in a VM now, and assuming there's something broken in the installer, I'll put out an update.

**Comment by Psychlist1972** [comment] 2024-01-16 04:56
@m-komo

It was a bad installer file. I'm so sorry.

Updated installer here
https://github.com/microsoft/MIDI/releases/tag/dev-preview-4-daily1

**Comment by m-komo** [comment] 2024-01-16 07:01
@Psychlist1972 

Thank you for updating the installer.
I successfully installed it on my PC.

Then I checked whether the issue persists and there were no out of order messages.
It seems the issue has been solved.

However, the message displayed by the monitor command is very slow. 
The device sends a message every 500 microseconds, so you should have received 10,000 messages after 5 seconds.
But the message displayed on the monitor was about 300 messages. 

Is this a limitation due to this fix?

**Comment by dmiura** [comment] 2024-01-16 08:24
@Psychlist1972

We've installed updated installer and confirming the issue again. 
As m-komo commented, monitor command is very slow...

**Comment by Psychlist1972** [comment] 2024-01-16 15:05
> @Psychlist1972
> 
> Thank you for updating the installer. I successfully installed it on my PC.
> 
> Then I checked whether the issue persists and there were no out of order messages. It seems the issue has been solved.
> 
> However, the message displayed by the monitor command is very slow. The device sends a message every 500 microseconds, so you should have received 10,000 messages after 5 seconds. But the message displayed on the monitor was about 300 messages.
> 
> Is this a limitation due to this fix?

There's a limit as to how fast messages can be output to the console. It should be much faster than in the past, but I didn't test overall time. I'll look at overall timing next.

**Comment by Psychlist1972** [comment] 2024-01-16 15:53
@dmiura  @m-komo 

I will look at further ways to optimize the console output speed. There's a limit as to how much can be done there, though.

However, because I had separated capture from display, I was able to add to the summary some information that shows me that the actual messages are being received in time, even if the display isn't keeping up.

![image](https://github.com/microsoft/MIDI/assets/1421146/77f9ccd7-e3f2-49d0-80b0-2d8fa09de022)

That is from pressing "5" on the protozoa. This is from pressing "3"

![image](https://github.com/microsoft/MIDI/assets/1421146/8cf6bdeb-09c9-47fa-9457-25f74161d535)

**Comment by Psychlist1972** [comment] 2024-01-16 19:03
Bit of a breakthrough here. By splitting out some steps to yet another thread, I was able to get the console to be within 5 or so messages being displayed vs captured.

![image](https://github.com/microsoft/MIDI/assets/1421146/19f33936-61ac-4912-80d4-d27934525840)

**Comment by Psychlist1972** [comment] 2024-01-16 19:33
@dmiura  @m-komo 

Please let me know if https://github.com/microsoft/MIDI/releases/tag/dev-preview-4-daily2 fixes this for you. I'll hold off on closing it as complete until then.

**Comment by m-komo** [comment] 2024-01-17 02:43
@Psychlist1972 

I checked the DP4 daily2.
I confirmed that the performance of console output is good and no out of order messages are received.
Thank you!

**Comment by Psychlist1972** [comment] 2024-01-17 03:33
> @Psychlist1972
> 
> I checked the DP4 daily2. I confirmed that the performance of console output is good and no out of order messages are displayed. Thank you!

Great, thank you!

@dmiura let me know if you also concur, in which case, I will close this bug as fixed.

**Comment by dmiura** [comment] 2024-01-17 06:57
@Psychlist1972 @m-komo

We checked DP4-daily2, it was succeeded 100,000 messages transmit with 500usec interval, unfortunately, second transmitting was failed.

We tried several sets of 100,000 messages transmitting, result is as below.
1st transmitting: succeeded. 
![Unknown-2](https://github.com/microsoft/MIDI/assets/8167750/f21a79e9-70b4-4b73-87bf-bbea1130a031)
2nd transmitting: not succeeded, 15 messages were lost.
![Unknown](https://github.com/microsoft/MIDI/assets/8167750/2b245b37-db5f-4321-b324-7eb6f5ea5711)
3rd transmitting: about 40% messages were lost, and receive duration became approximately 1000usec.
![Unknown-1](https://github.com/microsoft/MIDI/assets/8167750/6e4b4885-edf8-478c-8028-17c6d18f02f3)

**Comment by dmiura** [comment] 2024-01-17 08:43
@Psychlist1972
Do we need to install everything(OS, Developer Preview, etc) from scratch for testing?
We assume that something cache remained in our environment...

**Comment by m-komo** [comment] 2024-01-17 10:59
@Psychlist1972 @dmiura 

I've never seen this phenomenon "missing messages" with the 500usec interval, but it could be reproduced with the 100usec interval on my PC.

![image](https://github.com/microsoft/MIDI/assets/114042371/d1fd3169-0115-4294-9439-c30abf570d2b)

**Comment by Psychlist1972** [comment] 2024-01-17 15:38
> @Psychlist1972 Do we need to install everything(OS, Developer Preview, etc) from scratch for testing? We assume that something cache remained in our environment...

Not in my experience, no.

**Comment by Psychlist1972** [comment] 2024-01-17 15:40
> @Psychlist1972 @m-komo
> 
> We checked DP4-daily2, it was succeeded 100,000 messages transmit with 500usec interval, unfortunately, second transmitting was failed.
> 
> We tried several sets of 100,000 messages transmitting, result is as below. 1st transmitting: succeeded. ![Unknown-2](https://private-user-images.githubusercontent.com/8167750/297286959-f21a79e9-70b4-4b73-87bf-bbea1130a031.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDYwNjQsIm5iZiI6MTcwNTUwNTc2NCwicGF0aCI6Ii84MTY3NzUwLzI5NzI4Njk1OS1mMjFhNzllOS03MGI0LTRiNzMtODdiZi1iYmVhMTEzMGEwMzEuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE1MzYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MzNiNWUxNzBiNTgyYjY0OWU1YzFmMzg1OWE3OGE1ZTkwNWI1OTQxZGVlMzMyZDEzZmJmZjUzYTM4NWM5YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IFdETZxdd8r247JkYHkB7UsxGPn5pOx7fcvOJykbkdQ) 2nd transmitting: not succeeded, 15 messages were lost. ![Unknown](https://private-user-images.githubusercontent.com/8167750/297286332-2b245b37-db5f-4321-b324-7eb6f5ea5711.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDYwNjQsIm5iZiI6MTcwNTUwNTc2NCwicGF0aCI6Ii84MTY3NzUwLzI5NzI4NjMzMi0yYjI0NWIzNy1kYjVmLTQzMjEtYjMyNC03ZWI2ZjVlYTU3MTEuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE1MzYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYmIwY2M1ZjhjM2E4NGVhMjVjZTJhYzFhYTc5OGQ3MmUwNDMyMzhiMGU0MjVlYzIxZTgzMTdjNTY3NjEzZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NuWpLURb5aOWIsfe4MAo2PPfFRiWtk4LSsdHQx2Dmpc) 3rd transmitting: about 40% messages were lost, and receive duration became approximately 1000usec. ![Unknown-1](https://private-user-images.githubusercontent.com/8167750/297286703-6e4b4885-edf8-478c-8028-17c6d18f02f3.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDYwNjQsIm5iZiI6MTcwNTUwNTc2NCwicGF0aCI6Ii84MTY3NzUwLzI5NzI4NjcwMy02ZTRiNDg4NS1lZGY4LTQ3OGMtODAyOC0xN2M2ZDE4ZjAyZjMuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE1MzYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NmVjNzAwODNiNGIxNmY5NmQ0MDcwMzdmYzUwMjRmYWExNDRlZjMzMzkyNWI1NWMwMzgxZjk2MWI4YjMwMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jzucS_9aC2Nb5yo-nO7DdzScI0CeUVWfceeSsIyRUzk)
> 
> We'll check again tomorrow.

This is all good information. Thank you. I will look into it. 

During this test, did you use Control-C to end the console at all, or did you always use Escape? In the former case, the process is killed and the service buffers do not get cleaned up per #221

**Comment by Psychlist1972** [comment] 2024-01-17 15:42
(Note that you don't need to use `--verbose` for the tests. The data will fit on your screen better without it :))

**Comment by Psychlist1972** [comment] 2024-01-17 22:56
Incorrect data is no longer being received, so closing this issue.

I've created a new issue to track the missing message problem. See #227

**Closed** 2024-01-17 22:57 UTC
Labels: bug :lady_beetle:, area-user-tools :gear:

**Comment by dmiura** [comment] 2024-01-18 02:09
@Psychlist1972

> During this test, did you use Control-C to end the console at all, or did you always use Escape?

We used Control-C after 2nd transmitting before 3rd transmitting.

**Comment by Psychlist1972** [comment] 2024-01-18 02:25
> @Psychlist1972
> 
> > During this test, did you use Control-C to end the console at all, or did you always use Escape?
> 
> We used Control-C after 2nd transmitting before 3rd transmitting.

Thanks. Note that if you control-C or crash a client app, you usually need to restart the service for things to work reliably. That's not the cause of the skipped messages, but it can cause hang-ups. #221
