### ISSUE TITLE
[BUG] First word of received UMP packets via USB MIDI 2.0 driver are missing for some message types.

### ISSUE THREAD

**Issue by m-komo** [microsoft/MIDI#309] opened 2024-04-15 08:59 UTC
**Describe the bug**
When I receive NOOP message or Undefined message (message type=6,7,8,9,A,B,C,E) via an USB MIDI 2.0 device, the first word is missing.
This issue does not occur with loopback endpoints.

**To Reproduce**
1. Update ProtoZOA with the attached firmware ([ZOA-216.uf2.zip](https://github.com/microsoft/MIDI/files/14976471/ZOA-216.uf2.zip)).
This firmware loops back all received UMP packets to the host.
2. Update the driver to the USB MIDI 2.0 driver (UsbMidi2.sys).
3. Open midi.exe in two windows.
4. From one, monitor "ZOA-216".
5. From the other, send the attached message file "[NoopAndUndefined.txt](https://github.com/microsoft/MIDI/files/14976476/NoopAndUndefined.txt)" to "ZOA-216".

First word of sent messages are not displayed on the monitor.
![USBMIDI2EP](https://github.com/microsoft/MIDI/assets/114042371/d6c3f056-7136-4f40-98c3-121c643cb654)

**Expected behavior**
All sent messages are displayed on the monitor as is.
![LoopbackEP](https://github.com/microsoft/MIDI/assets/114042371/d5b66c83-0557-4267-9f0d-5c5ea148dd11)

**Screenshots**
I checked USB transaction and confirmed that all sent messages are looped back.
<img width="1280" alt="SendNoopAndUndefined" src="https://github.com/microsoft/MIDI/assets/114042371/eff3872b-13ce-4515-8e9c-4d89ddaad1f0">

**Installer Name or Version**
 - Service: Windows.MIDI.Services.Developer.Preview.5.x64.1.0.24066.2126.exe
 - Driver: Updated_USBMIDI2_10.0.1.4.zip

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OS Build: 26100.1

**Device information, if this is with an external MIDI device:**
 - Device: ProtoZOA w/attached firmware.
[ZOA-216.uf2.zip](https://github.com/microsoft/MIDI/files/14976471/ZOA-216.uf2.zip)

**Comment by AmeNote-Michael** [comment] 2024-06-24 20:09
Removed self as assignee as did not seem to be USB MIDI 2 driver issue. I have confirmed messages progress through latest driver.

**Comment by m-komo** [comment] 2024-07-18 07:33
I verified the issue with the latest service and driver.
It seems to work fine, but I have a thing to make sure.

If I run the procedure on the device working with the USB MIDI 2.0 driver, NOOP messages are omitted.

![image](https://github.com/user-attachments/assets/7ddc8dda-86e1-45a5-abed-97557d3d91b8)

It may be okay, but is it intended?

- Service: Windows.MIDI.Services.In-Box.Service.-.Developer.Preview.6.1.0.24194.2233-x64.exe
- Driver: [interim preview build] 240713-USBMidi2-x86-TESTSIGNED.zip (DriverVer = 07/13/2024,23.1.50.504)
- OS: Windows 11 24H2 (OS Build 26100.1150)

**Comment by Psychlist1972** [comment] 2024-07-18 18:47
@Amenote-Michael NOOP messages, deliberately sent, are valid data and should be kept. You'll need to change your checks there.

**Comment by AmeNote-Michael** [comment] 2024-07-19 04:44
@Psychlist1972 USB IN was incorrectly dropping NOOP for both USB MIDI 1.0 and USB MIDI 2.0. Moved to intended USB MIDI 1.0 only.

![image](https://github.com/user-attachments/assets/044e10c3-ecee-419a-907f-587276f4a25d)

Will be in next pull request.

**Comment by sat-okada** [comment] 2024-07-22 07:32
I have confirmed that this issue is resolved with latest driver.

My driver version is as follows. 
Driver Provider : USBMidi2
Driver Date : 2024-07-19
Driver Version : 23.22.46.475
(240719-USBMidi2-x86-TESTSIGNED)

**Comment by m-komo** [comment] 2024-07-30 07:37
I have confirmed that the issue was resolved.
- Service: Windows.MIDI.Services.In-Box.Service.-.Developer.Preview.6.1.0.24194.2233-x64.exe
- Driver: [interim preview build] 240719-USBMidi2-x86-TESTSIGNED.zip (DriverVer = 07/19/2024,23.22.46.475)
- OS: Windows 11 24H2 (OS Build 26100.1150)

**Closed** 2024-07-30 12:39 UTC
Labels: bug :lady_beetle:, area-usb-driver :computer:, critical ‼️
